name: DropWizard EndPoint Action workflow

on:
  workflow_dispatch:
    inputs:
      nodeType:
        required: false 
        description: Node type
      buildableBranchRegex:
        required: false 
        description: "buildableBranchRegex"
      deployableBranchRegex :
        required: false 
        description : "deployableBranchRegex"
      isDeployableBranch: 
        required: false 
        description : "isDeployableBranch"
      autoDeployTest: 
        required: false  
        default: false 
        description: "autoDeployTest"
      autoDeployStage: 
        required: false 
        default: false 
        description: "autoDeployProduction"
      autoDeployProduction: 
        required: false 
        default: false 
        description: "autoDeployProduction"       
      publishArtifactS: 
        required: false 
        default: false 
        description : "publishArtifacts"
      performanceTestEnvs:
        required: false 
        description : "an array of values like item1,item2,item3"
       
env:
  JOB_NAME : '' #${{ job.name }}
  NODE_TYPE : ${{ inputs.nodeType || 'dind-nocache' }}
  BUIDABLE_BRANCH_REGEX:  ${{ inputs.buildableBranchRegex || '.*' }}
  DEPLOYABLE_BRANCH_REGEX:  ${{ inputs.deployableBranchRegex || 'master' }}
  IS_DEPLOYABLE_BRANCH :   ${{ inputs.isDeployableBranch || 'master' }} #${GITHUB_REF#refs/heads/}
  IS_DEPLOYABLE : false 
  MAVEN_ARGS :  '' 
  DEPLOY_TEST :  ${{ inputs.autoDeployTest || 'false' }}
  DEPLOY_STAGE : ${{ inputs.autoDeployStage || 'false' }}
  DEPLOY_PROD : ${{ inputs.autoDeployProduction || 'false' }}
  DEPLOYMENT_DRAIN_TIME :  ${{ inputs.deploymentDrainTime || '0' }}
  PUBLISH_ARTIFACTS :  ${{ inputs.publishArtifacts ||  'false' }}
  VALIDATE_ONLY : false 
  OVERRIDE_VERSION : '' 
  MOT_APPLICAITON_NAME :  ${{ secrets.motApplicationName ||  'JOB_NAME' }}
  SLACK_WORKSPACE :  ${{ secrets.slackWorkspace ||   'eg' }}
  SLACK_NOTIFICATION_CHANNEL :  '' #additional 
  SLACK_CHANNEL_NAME :  ${{ secrets.slackChannelName ||   secrets.SLACK_NOTIFICATION_CHANNEL }}
  DEPLOYMENT_PLATFORM :  ${{ secrets.deploymentPlatform ||   'multipaas-vrbo' }}
jobs:
  dropwizard:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Check Performance Test Environments
        run: |
          echo "${{ env.NODE_TYPE }}" 
          
