name: DropWizard EndPoint Action workflow

on:
  workflow_dispatch:
    inputs:
      node_type:
        required: false
        description: Node type
      buildable_branch_regex:
        required: false 
        description: "buildableBranchRegex"
      deployable_branch_regex :
        required: false
        description : "deployableBranchRegex"
      is_deployable_branch: 
        required: false
        description : "isDeployableBranch"
        
  
env:
  NODE_TYPE : ${{ inputs.node_type || 'dind-nocache' }}
  BUIDABLE_BRANCH_REGEX:  ${{ inputs.buildable_branch_regex || '.*' }}
  DEPLOYABLE_BRANCH_REGEX:  ${{ inputs.deployable_branch_regex || 'master' }}
  IS_DEPLOYABLE_BRANCH :   ${{ inputs.is_deployable_branch || 'master' }}
  IS_DEPLOYABLE : false
  MAVEN_ARGS :  '' 
  DEPLOY_TEST :  ${{ inputs.deploy_test || 'dind-nocache' }}
jobs:
  dropwizard:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Check Performance Test Environments
        run: |
          echo "${{ env.NODE_TYPE }}" 
          
